### ISSUE TITLE
Breaks on Android 11

### ISSUE THREAD

**Issue by CiriousJoker** [simpleclub/firebase_rest_auth#12]
As per [this link](https://developer.android.com/about/versions/11/non-sdk-11), setUseSessionTickets() and a bunch of other methods have been deprecated as of Android 10. Android 11 fully disabled them by default. 

Not targeting Android 11 is a workaround, but you can't go back once you screwed up.

<details>
<summary>
logcat
</summary>

```
D/FirebaseRestAuthPlugin(12644): Method call: Auth#registerChangeListeners
W/knowledge.debu(12644): Accessing hidden method Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application; (greylist, reflection, allowed)
I/TetheringManager(12644): registerTetheringEventCallback:com.ciriousjoker.tag_my_knowledge.debug
W/knowledge.debu(12644): Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (greylist, reflection, allowed)
W/knowledge.debu(12644): Accessing hidden field Landroid/app/ActivityThread;->mActivities:Landroid/util/ArrayMap; (greylist, reflection, allowed)
W/knowledge.debu(12644): Accessing hidden field Landroid/app/ActivityThread$ActivityClientRecord;->paused:Z (greylist, reflection, allowed)
W/knowledge.debu(12644): Accessing hidden field Landroid/app/ActivityThread$ActivityClientRecord;->activity:Landroid/app/Activity; (greylist, reflection, allowed)
W/knowledge.debu(12644): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (greylist-max-q,core-platform-api, reflection, denied)
W/OkHttp  (12644): unable to load android socket classes
W/OkHttp  (12644): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  (12644): 	at java.lang.Class.getMethod(Class.java:2072)
W/OkHttp  (12644): 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
W/OkHttp  (12644): 	at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  (12644): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  (12644): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  (12644): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  (12644): 	at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  (12644): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  (12644): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  (12644): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  (12644): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  (12644): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  (12644): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.framework.rest.RestAuthProviderImpl.<init>(RestAuthProviderImpl.kt:66)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.framework.rest.RestAuthProviderImpl.<init>(RestAuthProviderImpl.kt:33)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.core.data.rest.models.FirebaseRestAuth$Companion.getInstance(FirebaseRestAuth.kt:29)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.framework.impl.AuthDataSourceImpl.<init>(AuthDataSourceImpl.kt:16)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.core.data.source.AuthDataSource$Companion.getInstance(AuthDataSource.kt:32)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.FirebaseRestAuthPlugin.getAuth(FirebaseRestAuthPlugin.kt:137)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.FirebaseRestAuthPlugin.access$getAuth(FirebaseRestAuthPlugin.kt:36)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.FirebaseRestAuthPlugin$registerChangeListeners$1.call(FirebaseRestAuthPlugin.kt:221)
W/OkHttp  (12644): 	at com.simpleclub.firebase_rest_auth.FirebaseRestAuthPlugin$registerChangeListeners$1.call(FirebaseRestAuthPlugin.kt:36)
W/OkHttp  (12644): 	at com.google.android.gms.tasks.zzy.run(com.google.android.gms:play-services-tasks@@17.2.0:2)
W/OkHttp  (12644): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/OkHttp  (12644): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/OkHttp  (12644): 	at java.lang.Thread.run(Thread.java:923)
W/knowledge.debu(12644): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
W/knowledge.debu(12644): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
W/knowledge.debu(12644): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
D/RestAuthProviderImpl(12644): currentUser = FirebaseRestAuthUser(idToken='[REDACTED]', refreshToken='[REDACTED]', isAnonymous=false, userId='eyoxoBf1t7ZGkdHRjmOdvS2iDhj1', expirationTime=1601587786, name='null', picture='null', email='test2@wmpb.de', emailVerified=false, providerId='password', providerInfo={email=[test2@wmpb.de]})
D/RestAuthProviderImpl(12644): addIdTokenListener: com.simpleclub.firebase_rest_auth.framework.impl.AuthDataSourceImpl$addAuthStateListener$1@c1c16d1
```
</details>

Apparently, `android.net.ssl.SSLSockets#setUseSessionTickets` is the new replacement, but okhttp3 doesn't make use of it.
As per [this](https://github.com/square/okhttp/issues/5816), 4.4.0 might fix this.

I'll see if I can make a PR to fix this.

**Comment by CiriousJoker** [comment]
4.4.0 actually seems to fix it. Right now, when I logged in, it gave a timeout for reading Firestore data, which is kind of weird. I'll see if this is reproducible during development over the next couple of days and then I'll make a PR
